version: "3.9"

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "5001:9000"   # API MinIO
      - "5002:9001"   # Web console MinIO
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./data/minio:/data

  fastapi:
    build: .
    container_name: fastapi-app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "7000:8000"
    depends_on:
      - minio
    environment:
      MINIO_ENDPOINT: "minio:9000"          # ✅ используем имя сервиса, а не localhost
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      MINIO_BUCKET: "fields-bucket"
      MINIO_SECURE: "false"
    volumes:
      - .:/app
