"""init

Revision ID: 64644b3f6018
Revises: 32da59369259
Create Date: 2025-08-21 16:54:20.194753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64644b3f6018'
down_revision: Union[str, Sequence[str], None] = '32da59369259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_cyrillic', sa.String(), nullable=False),
    sa.Column('soato_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_districts_id'), 'districts', ['id'], unique=False)
    op.create_table('farmers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tax_or_unique_number', sa.String(), nullable=False),
    sa.Column('owner_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('data_from', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmers_id'), 'farmers', ['id'], unique=False)
    op.create_table('pests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_cyrillic', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pests_id'), 'pests', ['id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_id'), 'photos', ['id'], unique=False)
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_cyrillic', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plants_id'), 'plants', ['id'], unique=False)
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_cyrillic', sa.String(), nullable=False),
    sa.Column('soato_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_id'), 'regions', ['id'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_type', sa.String(), nullable=False),
    sa.Column('surface', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.create_table('damage_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('low_min_value', sa.Float(), nullable=False),
    sa.Column('low_max_value', sa.Float(), nullable=False),
    sa.Column('medium_min_value', sa.Float(), nullable=False),
    sa.Column('medium_max_value', sa.Float(), nullable=False),
    sa.Column('high_min_value', sa.Float(), nullable=False),
    sa.Column('high_max_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('pest_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pest_id'], ['pests.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_damage_details_id'), 'damage_details', ['id'], unique=False)
    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('warehouse', sa.String(), nullable=True),
    sa.Column('farmer_id', sa.Integer(), nullable=True),
    sa.Column('unique_id', sa.String(), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('centroid', sa.JSON(), nullable=True),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('massiv_name', sa.String(), nullable=False),
    sa.Column('cadastre_number', sa.String(), nullable=False),
    sa.Column('ball_bonitet', sa.Float(), nullable=False),
    sa.Column('contour_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('data_from', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('risk', sa.String(), nullable=False),
    sa.Column('info', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    op.create_index(op.f('ix_fields_id'), 'fields', ['id'], unique=False)
    op.create_table('pest_photos',
    sa.Column('pest_id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pest_id'], ['pests.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('pest_id', 'photo_id')
    )
    op.create_table('damages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('damage_detail_id', sa.Integer(), nullable=True),
    sa.Column('ball', sa.Float(), nullable=False),
    sa.Column('risk', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['damage_detail_id'], ['damage_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_damages_id'), 'damages', ['id'], unique=False)
    op.create_table('monitorings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('checked_location', sa.JSON(), nullable=True),
    sa.Column('plant_area', sa.Float(), nullable=False),
    sa.Column('checked_area', sa.Float(), nullable=False),
    sa.Column('is_after_cleared', sa.Boolean(), nullable=True),
    sa.Column('is_clear', sa.Boolean(), nullable=True),
    sa.Column('monitoring_time', sa.DateTime(), nullable=False),
    sa.Column('risk', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitorings_id'), 'monitorings', ['id'], unique=False)
    op.create_table('plant_monitorings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('monitoring_id', sa.Integer(), nullable=True),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('risk', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['monitoring_id'], ['monitorings.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plant_monitorings_id'), 'plant_monitorings', ['id'], unique=False)
    op.create_table('plant_monitoring_photos',
    sa.Column('plant_monitoring_id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.ForeignKeyConstraint(['plant_monitoring_id'], ['plant_monitorings.id'], ),
    sa.PrimaryKeyConstraint('plant_monitoring_id', 'photo_id')
    )
    op.create_table('struggles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pest_id', sa.Integer(), nullable=True),
    sa.Column('damage_id', sa.Integer(), nullable=True),
    sa.Column('plant_monitoring_id', sa.Integer(), nullable=True),
    sa.Column('struggle_type', sa.String(), nullable=False),
    sa.Column('spread_area', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['damage_id'], ['damages.id'], ),
    sa.ForeignKeyConstraint(['pest_id'], ['pests.id'], ),
    sa.ForeignKeyConstraint(['plant_monitoring_id'], ['plant_monitorings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_struggles_id'), 'struggles', ['id'], unique=False)
    op.create_table('struggle_photos',
    sa.Column('struggle_id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.ForeignKeyConstraint(['struggle_id'], ['struggles.id'], ),
    sa.PrimaryKeyConstraint('struggle_id', 'photo_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('struggle_photos')
    op.drop_index(op.f('ix_struggles_id'), table_name='struggles')
    op.drop_table('struggles')
    op.drop_table('plant_monitoring_photos')
    op.drop_index(op.f('ix_plant_monitorings_id'), table_name='plant_monitorings')
    op.drop_table('plant_monitorings')
    op.drop_index(op.f('ix_monitorings_id'), table_name='monitorings')
    op.drop_table('monitorings')
    op.drop_index(op.f('ix_damages_id'), table_name='damages')
    op.drop_table('damages')
    op.drop_table('pest_photos')
    op.drop_index(op.f('ix_fields_id'), table_name='fields')
    op.drop_table('fields')
    op.drop_index(op.f('ix_damage_details_id'), table_name='damage_details')
    op.drop_table('damage_details')
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_regions_id'), table_name='regions')
    op.drop_table('regions')
    op.drop_index(op.f('ix_plants_id'), table_name='plants')
    op.drop_table('plants')
    op.drop_index(op.f('ix_photos_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_pests_id'), table_name='pests')
    op.drop_table('pests')
    op.drop_index(op.f('ix_farmers_id'), table_name='farmers')
    op.drop_table('farmers')
    op.drop_index(op.f('ix_districts_id'), table_name='districts')
    op.drop_table('districts')
    # ### end Alembic commands ###
